trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 06-angular/pokemon-app

pool:
  name: Default

variables:
  appDir: 06-angular/pokemon-app

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '>=10'
    checkLatest: true
  displayName: Install Node.js

- script: npm ci
  workingDirectory: $(appDir)
  displayName: npm ci

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  inputs:
    SonarCloud: sonarcloud
    organization: 1902-feb18-net
    scannerMode: CLI
  displayName: Prepare analysis on SonarCloud

- script: npm run build-ci
  workingDirectory: $(appDir)
  displayName: npm run build-ci

- script: npm run lint
  workingDirectory: $(appDir)
  displayName: npm run lint

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: Run code analysis

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: Publish quality gate result

- task: AzureRmWebAppDeployment@4
  displayName: Azure App Service deploy
  inputs:
    azureSubscription: nick-azure
    WebAppName: escalona1902pokeangular
    packageForLinux: $(appDir)/dist/pokemon-app
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(appDir)/dist/pokemon-app
    artifactName: app
  displayName: Publish app artifact
