trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 06-angular/pokemon-app

pool: 'Default'

variables:
  appDir: 06-angular/pokemon-app

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    # install/update angular cli globally on the agent
    # npm install -g @angular/cli
    # install local dependencies from package-lock.json
    npm ci
    # build in production configuration, which activates
    # certain rules in angular.json (e.g. replace environment.ts
    # with environment.prod.ts)
    npm run build --prod
  workingDirectory: $(appDir)
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  displayName: Azure App Service deploy
  inputs:
    azureSubscription: nick-azure
    WebAppName: escalona1902pokeangular
    packageForLinux: $(appDir)/dist/pokemon-app
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
